### ISSUE TITLE
Settings pattern: content actions select icon not positioned correctly

### ISSUE THREAD

**Issue by jackbentley** [jadu/pulsar#1246]
**Describe the bug**
The page controls in the "content actions" on the settings pattern doesn't have its icon positioned correctly.

This code looks related: https://github.com/jadu/pulsar/blob/6dae8a1001dfb2b7ef9d6724379b9fa6aa9a0ff5/stylesheets/_layout.settings.scss#L450-L453

**To Reproduce**
Steps to reproduce the behaviour:
1. Load the publish tab in XFP

**Expected behaviour**
The icon should be positioned correctly in the smaller than usual select.

**Screenshots**
<img width="568" alt="Screen Shot 2020-06-01 at 12 44 51" src="https://user-images.githubusercontent.com/9383439/83408240-35f37f80-a40a-11ea-8bfd-d1e4d67a082f.png">

**Comment by jackbentley** [comment]
Probably worth noting that in the lexicon example of this UI, the select doesn't have a label attached to it. I've changed the "Page" text to be the label of the input but this has required additional CSS in order to remove the padding etc on the `control__label`:

```css
.content-actions__pages .control__label {
    padding: 0;
    width: auto;
    display: inline;
    vertical-align: unset;
}
```
