### ISSUE TITLE
Test toggle switch layout when used in settings sidebar UI

### ISSUE THREAD

**Issue by Stanton** [jadu/pulsar#904]
Issues seen in XFP and currently require override styles.

**Comment by Stanton** [comment]
Pulsar may require the following styles:

```.tab__settings .form__group--toggle .controls {
  float: right !important; }

.tab__settings .form__group--toggle > .control__label, .tab__settings .form__group--toggle span.control__label {
  width: auto !important;
  max-width: 75%; }

.tab__settings .form__group--toggle::after {
  content: '';
  display: table;
  clear: both; }```

**Comment by jackbentley** [comment]
SCSS for that CSS above (it's from XFP):
```scss
.tab__settings .form__group--toggle {
    & .controls {
        float: right !important;
    }

    & > .control__label, & span.control__label {
        width: auto !important;
        max-width: 75%;
    }

    &::after {
        content: '';
        display: table;
        clear: both;
    }
}
```
